M48
; DRILL file {KiCad (7.0.0)} date Fri May 19 14:17:52 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-19T14:17:52+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.1688Y-5.1505
X5.5045Y-3.6561
X6.4281Y-2.8975
X6.4281Y-5.0975
T0
M30
